[package]
name = "fmod-studio-examples"
version = "1.0.0"
edition = "2021"
publish = false

[lib]
name = "common"

[dependencies]
crossterm = "0.27.0"
fmod-oxide = { version = "2.2.0", path = "../fmod-oxide/" }
bitflags = "2.5.0"
