// Copyright (c) 2024 Lily Lyons
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

use fmod_sys::*;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[derive(
    num_enum::TryFromPrimitive,
    num_enum::IntoPrimitive,
    num_enum::UnsafeFromPrimitive
)]
#[repr(u32)]
pub enum SpeakerMode {
    Default = FMOD_SPEAKERMODE_FMOD_SPEAKERMODE_DEFAULT,
    Raw = FMOD_SPEAKERMODE_FMOD_SPEAKERMODE_RAW,
    Mono = FMOD_SPEAKERMODE_FMOD_SPEAKERMODE_MONO,
    Stereo = FMOD_SPEAKERMODE_FMOD_SPEAKERMODE_STEREO,
    Quad = FMOD_SPEAKERMODE_FMOD_SPEAKERMODE_QUAD,
    Surround = FMOD_SPEAKERMODE_FMOD_SPEAKERMODE_SURROUND,
    FivePointOne = FMOD_SPEAKERMODE_FMOD_SPEAKERMODE_5POINT1,
    SevenPointOne = FMOD_SPEAKERMODE_FMOD_SPEAKERMODE_7POINT1,
    SevenPointOneFour = FMOD_SPEAKERMODE_FMOD_SPEAKERMODE_7POINT1POINT4,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[derive(
    num_enum::TryFromPrimitive,
    num_enum::IntoPrimitive,
    num_enum::UnsafeFromPrimitive
)]
#[repr(u32)]
pub enum OutputType {
    AutoDetect = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_AUTODETECT,
    Unknown = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_UNKNOWN,
    NoSound = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_NOSOUND,
    WavWriter = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_WAVWRITER,
    NoSoundNRT = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_NOSOUND_NRT,
    WavWriterNRT = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_WAVWRITER_NRT,
    WASAPI = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_WASAPI,
    ASIO = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_ASIO,
    PulseAudio = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_PULSEAUDIO,
    Alsa = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_ALSA,
    CoreAudio = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_COREAUDIO,
    AudioTrack = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_AUDIOTRACK,
    OpenSL = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_OPENSL,
    AudioOut = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_AUDIOOUT,
    WebAudio = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_WEBAUDIO,
    NNAudio = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_NNAUDIO,
    WinSonic = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_WINSONIC,
    AAudio = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_AAUDIO,
    AudioWorklet = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_AUDIOWORKLET,
    Phase = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_PHASE,
    OHAudio = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_OHAUDIO,
}
