// Copyright (c) 2024 Lily Lyons
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

use fmod_sys::*;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[derive(
    num_enum::TryFromPrimitive,
    num_enum::IntoPrimitive,
    num_enum::UnsafeFromPrimitive
)]
#[repr(u32)]
pub enum SpeakerMode {
    Default = FMOD_SPEAKERMODE_FMOD_SPEAKERMODE_DEFAULT,
    Raw = FMOD_SPEAKERMODE_FMOD_SPEAKERMODE_RAW,
    Mono = FMOD_SPEAKERMODE_FMOD_SPEAKERMODE_MONO,
    Stereo = FMOD_SPEAKERMODE_FMOD_SPEAKERMODE_STEREO,
    Quad = FMOD_SPEAKERMODE_FMOD_SPEAKERMODE_QUAD,
    Surround = FMOD_SPEAKERMODE_FMOD_SPEAKERMODE_SURROUND,
    FivePointOne = FMOD_SPEAKERMODE_FMOD_SPEAKERMODE_5POINT1,
    SevenPointOne = FMOD_SPEAKERMODE_FMOD_SPEAKERMODE_7POINT1,
    SevenPointOneFour = FMOD_SPEAKERMODE_FMOD_SPEAKERMODE_7POINT1POINT4,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[derive(
    num_enum::TryFromPrimitive,
    num_enum::IntoPrimitive,
    num_enum::UnsafeFromPrimitive
)]
#[repr(u32)]
pub enum OutputType {
    AutoDetect = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_AUTODETECT,
    Unknown = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_UNKNOWN,
    NoSound = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_NOSOUND,
    WavWriter = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_WAVWRITER,
    NoSoundNRT = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_NOSOUND_NRT,
    WavWriterNRT = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_WAVWRITER_NRT,
    WASAPI = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_WASAPI,
    ASIO = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_ASIO,
    PulseAudio = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_PULSEAUDIO,
    Alsa = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_ALSA,
    CoreAudio = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_COREAUDIO,
    AudioTrack = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_AUDIOTRACK,
    OpenSL = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_OPENSL,
    AudioOut = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_AUDIOOUT,
    WebAudio = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_WEBAUDIO,
    NNAudio = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_NNAUDIO,
    WinSonic = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_WINSONIC,
    AAudio = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_AAUDIO,
    AudioWorklet = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_AUDIOWORKLET,
    Phase = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_PHASE,
    OHAudio = FMOD_OUTPUTTYPE_FMOD_OUTPUTTYPE_OHAUDIO,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[derive(
    num_enum::TryFromPrimitive,
    num_enum::IntoPrimitive,
    num_enum::UnsafeFromPrimitive
)]
#[repr(u32)]
pub enum ThreadType {
    Mixer = FMOD_THREAD_TYPE_FMOD_THREAD_TYPE_MIXER,
    Feeder = FMOD_THREAD_TYPE_FMOD_THREAD_TYPE_FEEDER,
    Stream = FMOD_THREAD_TYPE_FMOD_THREAD_TYPE_STREAM,
    File = FMOD_THREAD_TYPE_FMOD_THREAD_TYPE_FILE,
    NonBlocking = FMOD_THREAD_TYPE_FMOD_THREAD_TYPE_NONBLOCKING,
    Record = FMOD_THREAD_TYPE_FMOD_THREAD_TYPE_RECORD,
    Geometry = FMOD_THREAD_TYPE_FMOD_THREAD_TYPE_GEOMETRY,
    Profiler = FMOD_THREAD_TYPE_FMOD_THREAD_TYPE_PROFILER,
    StudioUpdate = FMOD_THREAD_TYPE_FMOD_THREAD_TYPE_STUDIO_UPDATE,
    StudioLoadBank = FMOD_THREAD_TYPE_FMOD_THREAD_TYPE_STUDIO_LOAD_BANK,
    StudioLoadSample = FMOD_THREAD_TYPE_FMOD_THREAD_TYPE_STUDIO_LOAD_SAMPLE,
    Convolution1 = FMOD_THREAD_TYPE_FMOD_THREAD_TYPE_CONVOLUTION1,
    Convolution2 = FMOD_THREAD_TYPE_FMOD_THREAD_TYPE_CONVOLUTION2,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[derive(
    num_enum::TryFromPrimitive,
    num_enum::IntoPrimitive,
    num_enum::UnsafeFromPrimitive
)]
#[repr(u32)]
pub enum TimeUnit {
    MS = FMOD_TIMEUNIT_MS,
    PCM = FMOD_TIMEUNIT_PCM,
    PCMBytes = FMOD_TIMEUNIT_PCMBYTES,
    RAWBytes = FMOD_TIMEUNIT_RAWBYTES,
    PCMFraction = FMOD_TIMEUNIT_PCMFRACTION,
    ModOrder = FMOD_TIMEUNIT_MODORDER,
    ModRow = FMOD_TIMEUNIT_MODROW,
    ModPattern = FMOD_TIMEUNIT_MODPATTERN,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[derive(
    num_enum::TryFromPrimitive,
    num_enum::IntoPrimitive,
    num_enum::UnsafeFromPrimitive
)]
#[repr(i32)]
pub enum Speaker {
    None = FMOD_SPEAKER_FMOD_SPEAKER_NONE,
    FrontLeft = FMOD_SPEAKER_FMOD_SPEAKER_FRONT_LEFT,
    FrontRight = FMOD_SPEAKER_FMOD_SPEAKER_FRONT_RIGHT,
    FrontCenter = FMOD_SPEAKER_FMOD_SPEAKER_FRONT_CENTER,
    LowFrequency = FMOD_SPEAKER_FMOD_SPEAKER_LOW_FREQUENCY,
    SurroundLeft = FMOD_SPEAKER_FMOD_SPEAKER_SURROUND_LEFT,
    SurroundRight = FMOD_SPEAKER_FMOD_SPEAKER_SURROUND_RIGHT,
    BackLeft = FMOD_SPEAKER_FMOD_SPEAKER_BACK_LEFT,
    BackRight = FMOD_SPEAKER_FMOD_SPEAKER_BACK_RIGHT,
    TopFrontLeft = FMOD_SPEAKER_FMOD_SPEAKER_TOP_FRONT_LEFT,
    TopFrontRight = FMOD_SPEAKER_FMOD_SPEAKER_TOP_FRONT_RIGHT,
    TopBackLeft = FMOD_SPEAKER_FMOD_SPEAKER_TOP_BACK_LEFT,
    TopBackRight = FMOD_SPEAKER_FMOD_SPEAKER_TOP_BACK_RIGHT,
}
